// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sunergy.Data.Context;

#nullable disable

namespace Sunergy.Data.Migrations
{
    [DbContext(typeof(SolarContext))]
    [Migration("20250113183519_AddedPanelWeatherAndPanelWeatherHoursTable")]
    partial class AddedPanelWeatherAndPanelWeatherHoursTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sunergy.Data.Model.PanelWeather", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AverageCloudiness")
                        .HasColumnType("float");

                    b.Property<double>("AverageTemp")
                        .HasColumnType("float");

                    b.Property<DateTime>("Day")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PanelId")
                        .HasColumnType("int");

                    b.Property<double>("Produced")
                        .HasColumnType("float");

                    b.Property<DateTime?>("SunriseTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SunsetTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PanelId");

                    b.ToTable("PanelWeathers");
                });

            modelBuilder.Entity("Sunergy.Data.Model.PanelWeatherHours", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Cloudiness")
                        .HasColumnType("float");

                    b.Property<double>("CurrentPrice")
                        .HasColumnType("float");

                    b.Property<double>("Earning")
                        .HasColumnType("float");

                    b.Property<bool>("IsDay")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PanelWeatherId")
                        .HasColumnType("int");

                    b.Property<double>("Produced")
                        .HasColumnType("float");

                    b.Property<double>("SunDurationPercentage")
                        .HasColumnType("float");

                    b.Property<double>("Temperature")
                        .HasColumnType("float");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PanelWeatherId");

                    b.ToTable("PanelWeatherHours");
                });

            modelBuilder.Entity("Sunergy.Data.Model.SolarPowerPlant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Efficiency")
                        .HasColumnType("float");

                    b.Property<double?>("InstalledPower")
                        .HasColumnType("float");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PanelType")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PowerPlants");
                });

            modelBuilder.Entity("Sunergy.Data.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Sunergy.Data.Model.PanelWeather", b =>
                {
                    b.HasOne("Sunergy.Data.Model.SolarPowerPlant", "Panel")
                        .WithMany("PanelWeathers")
                        .HasForeignKey("PanelId");

                    b.Navigation("Panel");
                });

            modelBuilder.Entity("Sunergy.Data.Model.PanelWeatherHours", b =>
                {
                    b.HasOne("Sunergy.Data.Model.PanelWeather", "PanelWeather")
                        .WithMany("Hours")
                        .HasForeignKey("PanelWeatherId");

                    b.Navigation("PanelWeather");
                });

            modelBuilder.Entity("Sunergy.Data.Model.SolarPowerPlant", b =>
                {
                    b.HasOne("Sunergy.Data.Model.User", "User")
                        .WithMany("SolarPanels")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sunergy.Data.Model.PanelWeather", b =>
                {
                    b.Navigation("Hours");
                });

            modelBuilder.Entity("Sunergy.Data.Model.SolarPowerPlant", b =>
                {
                    b.Navigation("PanelWeathers");
                });

            modelBuilder.Entity("Sunergy.Data.Model.User", b =>
                {
                    b.Navigation("SolarPanels");
                });
#pragma warning restore 612, 618
        }
    }
}
